-- Stage 2/2: Property photos metadata table for BuySel
create table if not exists public.propertyphotos (
  id bigint generated by default as identity primary key,
  propertyid bigint not null,
  photobloburl text not null,
  title text not null,
  doc boolean,
  dte timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint propertyphotos_propertyid_fkey
    foreign key (propertyid)
    references public.properties(id)
    on delete cascade
);

create index if not exists idx_propertyphotos_propertyid on public.propertyphotos(propertyid);
create index if not exists idx_propertyphotos_dte on public.propertyphotos(dte desc);

create or replace function public.set_updated_at_propertyphotos()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_propertyphotos on public.propertyphotos;
create trigger trg_set_updated_at_propertyphotos
before update on public.propertyphotos
for each row
execute function public.set_updated_at_propertyphotos();
