-- Stage 1/2: Supabase profile storage schema for BuySel
create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  firstname text,
  lastname text,
  middlename text,
  dateofbirth timestamptz,
  mobile text,
  address text,
  residencystatus text check (residencystatus in ('citizen', 'permanent', 'temporary', 'foreign', '')),
  maritalstatus text check (maritalstatus in ('single', 'married', 'divorced', 'widowed', 'defacto')),
  powerofattorney text,
  idtype text default 'none' check (idtype in ('passport', 'driver', 'none')),
  idbloburl text,
  idverified timestamptz,
  termsconditions boolean default false,
  privacypolicy boolean default false,
  dte timestamptz default now(),
  ratesnotice text,
  titlesearch text,
  ratesnoticeverified timestamptz,
  titlesearchverified timestamptz,
  photoazurebloburl text,
  photoverified timestamptz,
  role text default 'user',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function public.set_updated_at_user_profiles()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_user_profiles on public.user_profiles;
create trigger trg_set_updated_at_user_profiles
before update on public.user_profiles
for each row
execute function public.set_updated_at_user_profiles();

create index if not exists idx_user_profiles_email on public.user_profiles(email);

create or replace function public.sync_user_profiles_id_sequence()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  max_id bigint;
begin
  select coalesce(max(id), 0) into max_id from public.user_profiles;
  perform setval(pg_get_serial_sequence('public.user_profiles', 'id'), max_id, true);
  return max_id;
end;
$$;
